import {preparePresentation} from './src/demo-presentation.mjs';
import {ensureDemoPhoto} from './src/demo-photo.mjs';
import {mkdir,writeFile,readFile,unlink} from 'node:fs/promises';
import {createServer} from 'node:http';import {DatabaseSync} from 'node:sqlite';import {readFileSync,existsSync,readdirSync,mkdirSync,writeFileSync} from 'node:fs';import {handle} from './src/auth.mjs';import {seedTest} from './src/test-seed.mjs';
const sqlite=new DatabaseSync(process.env.ELECTION_DB||'elections.sqlite');sqlite.exec('CREATE TABLE IF NOT EXISTS local_migrations(name TEXT PRIMARY KEY)');for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort()){if(sqlite.prepare('SELECT name FROM local_migrations WHERE name=?').get(file))continue;if(file.startsWith('0000_')&&sqlite.prepare("SELECT name FROM sqlite_master WHERE name='schools'").get()){sqlite.prepare('INSERT INTO local_migrations(name) VALUES(?)').run(file);continue;}sqlite.exec('BEGIN');try{sqlite.exec(readFileSync('drizzle/'+file,'utf8'));sqlite.prepare('INSERT INTO local_migrations(name) VALUES(?)').run(file);sqlite.exec('COMMIT');}catch(e){sqlite.exec('ROLLBACK');throw e;}}
const db={prepare(sql){let values=[];return{bind(...a){values=a;return this},async first(){return sqlite.prepare(sql).get(...values)},async all(){return{results:sqlite.prepare(sql).all(...values)}},async run(){return{meta:{changes:sqlite.prepare(sql).run(...values).changes}}}}},async batch(statements){sqlite.exec('BEGIN');try{let result=[];for(let statement of statements)result.push(await statement.run());sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
const photoPath=key=>{if(!/^[a-zA-Z0-9-]+\/[-a-zA-Z0-9]+\.jpg$/.test(key))throw Error('Invalid photo key');return (process.env.PHOTO_DIRECTORY||'.uploads')+'/'+key};const storage={async put(key,bytes){const path=photoPath(key);await mkdir(path.slice(0,path.lastIndexOf('/')),{recursive:true,mode:0o700});await writeFile(path,bytes,{mode:0o600})},async get(key){try{const bytes=await readFile(photoPath(key));return {arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)}}catch(e){if(e.code==='ENOENT')return null;throw e}},async delete(key){await unlink(photoPath(key))}};
const env={PHOTOS:storage,...process.env,APP_URL:process.env.APP_URL||'http://localhost:3000'};if(env.EMAIL_CAPTURE==='true'){env.MAILER=async message=>{mkdirSync('.mail',{recursive:true,mode:0o700});writeFileSync('.mail/'+crypto.randomUUID()+'.json',JSON.stringify(message,null,2),{mode:0o600});};}await seedTest(db,env.TEST_SEED_JSON,env.LEGACY_OWNER_ID);await preparePresentation(db,env.TEST_SEED_JSON,env.DEMO_PRESENTATION_JSON);await ensureDemoPhoto(db,env.PHOTOS,env.TEST_SEED_JSON,async()=>readFileSync('public/demo-candidate.jpg'));if(env.TEST_SEED_JSON&&env.DEMO_PRESENTATION_JSON){const seed=JSON.parse(env.TEST_SEED_JSON),prep=JSON.parse(env.DEMO_PRESENTATION_JSON);for(const schoolId of [prep.schoolBId,prep.schoolCId])await ensureDemoPhoto(db,env.PHOTOS,{...seed,schoolId},async()=>readFileSync('public/demo-candidate.jpg'));}
createServer(async(req,res)=>{try{const origin=env.APP_URL,p=new URL(req.url,origin).pathname;if(p.startsWith('/api/')){let chunks=[],size=0;for await(let chunk of req){size+=chunk.length;if(size>(p==='/api/state'?131072:32768)){res.writeHead(413);res.end();return}chunks.push(chunk);}let headers={...req.headers};delete headers['cf-connecting-ip'];headers['CF-Connecting-IP']=req.socket.remoteAddress;let request=new Request(origin+req.url,{method:req.method,headers,...(req.method==='POST'?{body:Buffer.concat(chunks)}:{})});let r=await handle(request,db,env);res.writeHead(r.status,Object.fromEntries(r.headers));res.end(await r.text());}else{let f=p==='/'?'index.html':p.slice(1);if(!/^[a-zA-Z0-9.\-]+$/.test(f)||!existsSync('public/'+f)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':f.endsWith('.js')?'text/javascript':f.endsWith('.svg')?'image/svg+xml':f.endsWith('.mp3')?'audio/mpeg':'image/jpeg');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.end(readFileSync('public/'+f));}}catch(e){console.error('Falha no servidor:',e.name);res.writeHead(500);res.end('Serviço indisponível.');}}).listen(Number(env.PORT||3000),env.HOST||'0.0.0.0',()=>console.log(env.APP_URL));
