import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {readFileSync,readdirSync} from 'node:fs';import {handle,passwordHash,randomToken,digest,sendMail,mailReady} from './src/auth.mjs';import {seedTest} from './src/test-seed.mjs';
const sqlite=new DatabaseSync(':memory:');for(let f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+f,'utf8'));const db={prepare(q){let args=[];return{bind(...a){args=a;return this},async first(){return sqlite.prepare(q).get(...args)},async all(){return{results:sqlite.prepare(q).all(...args)}},async run(){return{meta:{changes:sqlite.prepare(q).run(...args).changes}}}}},async batch(statements){sqlite.exec('BEGIN');try{let rows=[];for(let s of statements)rows.push(await s.run());sqlite.exec('COMMIT');return rows;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};let mail=[],session='';const env={APP_URL:'https://school.test',MAILER:async m=>mail.push(m)};
async function call(path,data,{status=200,cookie=session,origin=env.APP_URL,config=env}={}){let r=await handle(new Request(env.APP_URL+'/api/'+path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie},...(data?{body:JSON.stringify(data)}:{})}),db,config),d=await r.json();assert.equal(r.status,status,JSON.stringify(d));return{data:d,cookie:r.headers.get('Set-Cookie')?.split(';')[0]};}
const email='gestor.teste@enova.educacao.ba.gov.br',password='Senha-inicial-123';await call('auth/register',{email:'x@enova.educacao.ba.gov.br.evil.test',password},{status:400});await call('auth/register',{email,name:'Gestor fictício',password,schoolName:'Escola Teste',city:'Salvador'},{status:201});assert.equal(mail.length,1);let verifyToken=mail[0].text.split('#verify=')[1];assert(sqlite.prepare('SELECT password_hash FROM users').get().password_hash!==password);await call('auth/login',{email,password},{status:403});await call('auth/verify',{token:verifyToken});await call('auth/verify',{token:verifyToken},{status:400});session=(await call('auth/login',{email,password})).cookie;assert(session);assert((await call('auth/me')).data.user.verified);let schools=(await call('schools')).data;assert.equal(schools.length,1);await call('schools',{name:'wrong-origin',city:'Salvador'},{origin:'https://evil.test',status:403});await call('state?school='+schools[0].id,null,{cookie:'',status:401});let oldSession=session;await call('auth/change-password',{currentPassword:'wrong',password:'Senha-mudada-123'},{status:400});await call('auth/change-password',{currentPassword:password,password:'Senha-mudada-123'});assert.equal((await call('auth/me',null,{cookie:oldSession})).data.user,null);await call('auth/login',{email,password},{status:401});session=(await call('auth/login',{email,password:'Senha-mudada-123'})).cookie;await call('auth/forgot',{email});let reset=mail.at(-1).text.split('#reset=')[1];await call('auth/reset',{token:reset,password:'Nova-senha-reset-123'});await call('auth/reset',{token:reset,password:'Nova-senha-reset-123'},{status:400});assert.equal((await call('auth/me')).data.user,null);session=(await call('auth/login',{email,password:'Nova-senha-reset-123'})).cookie;await call('auth/logout',{});assert.equal((await call('auth/me')).data.user,null);
let id=crypto.randomUUID(),salt=randomToken(),seed={id,schoolId:crypto.randomUUID(),email:'teste.seed@enova.educacao.ba.gov.br',name:'Teste',salt,hash:await passwordHash('1234',salt)};await seedTest(db,seed);await seedTest(db,seed);session=(await call('auth/login',{email:seed.email,password:'1234'})).cookie;assert((await call('auth/me')).data.user.mustChange);await call('schools',null,{status:403});await call('auth/change-password',{currentPassword:'1234',password:'Senha-teste-alterada'});session=(await call('auth/login',{email:seed.email,password:'Senha-teste-alterada'})).cookie;let data=(await call('schools')).data;assert.equal(data.length,1);await call('state?school='+schools[0].id,null,{status:400});let school=(await call('state?school='+data[0].id)).data;assert.equal(school.classes.length,3);assert.equal(school.rounds[1].candidates.length,10);
await call('auth/register',{email:'pendente@enova.educacao.ba.gov.br',name:'Pendente',password,schoolName:'Outra',city:'Salvador'},{status:201,config:{APP_URL:env.APP_URL}});await call('auth/forgot',{email},{status:503,config:{APP_URL:env.APP_URL}});for(let i=0;i<10;i++)await call('auth/login',{email:'bloqueio@enova.educacao.ba.gov.br',password:'errada'},{status:401});await call('auth/login',{email:'bloqueio@enova.educacao.ba.gov.br',password:'errada'},{status:429});
console.log('PASS auth: domínio exato, confirmação e recuperação de uso único, sessão HttpOnly, CSRF, troca de senha, revogação, isolamento de escolas, seed idempotente, senha inicial e limite de tentativas.');

// Transport contract and free-plan limit; never send a real message in tests.
const originalFetch=globalThis.fetch;let requests=[];const brevo={APP_URL:env.APP_URL,EMAIL_PROVIDER:'brevo',BREVO_API_KEY:'fake-api-key',EMAIL_FROM:'sender@example.invalid'};
try {globalThis.fetch=async(url,options)=>{requests.push({url,options});return Response.json({messageId:'test-id'},{status:201})};assert(mailReady(brevo));assert(!mailReady({...brevo,BREVO_API_KEY:''}));await sendMail(brevo,email,'verify','a'.repeat(64));await sendMail(brevo,email,'reset','b'.repeat(64));assert.equal(requests[0].url,'https://api.brevo.com/v3/smtp/email');const payload=JSON.parse(requests[0].options.body);assert.equal(payload.to[0].email,email);assert.equal(payload.to[0].contactPixelTrackingConsent,false);assert.equal(payload.sender.email,brevo.EMAIL_FROM);assert(payload.textContent.includes('#verify='));assert(!('htmlContent' in payload));assert.deepEqual(Object.keys(payload).sort(),['sender','subject','textContent','to']);assert(JSON.parse(requests[1].options.body).textContent.includes('#reset='));
const day=Math.floor(Date.now()/1000/86400);sqlite.prepare('INSERT INTO rate_limits(key,count,expires_at) VALUES(?,300,?)').run('email-brevo:'+day,(day+1)*86400);const before=requests.length;await call('auth/forgot',{email},{config:brevo,status:503});assert.equal(requests.length,before);
globalThis.fetch=async()=>Response.json({error:'service unavailable'},{status:503});await assert.rejects(()=>sendMail(brevo,email,'verify','c'.repeat(64)),/Falha do remetente 503/);
console.log('PASS Brevo: API HTTPS, conteúdo mínimo, chave no servidor, links de acesso, falha explícita e limite de 300 tentativas/dia sem fallback pago.');}finally{globalThis.fetch=originalFetch;}

// Invalid guesses must stop before evaluating even a valid code once blocked.
school=(await call('state?school='+data[0].id)).data;await call('state',{school:school.id,type:'open'});school=(await call('state?school='+school.id)).data;for(let i=0;i<20;i++)await call('ballot',{school:school.id,code:'invalid'},{cookie:'',status:400});await call('ballot',{school:school.id,code:school.rounds[1].tokens[0].code},{cookie:'',status:429});assert.equal((await call('state?school='+school.id)).data.rounds[1].turnout,0);console.log('PASS proteção da urna: limite de tentativas inválidas sem bloquear requisições comuns da gestão.');
// The candidate photo exceeds the former 32 KB JSON limit; routes still require ownership.
const photoFiles=new Map();env.PHOTOS={async put(key,bytes){photoFiles.set(key,bytes)},async get(key){const bytes=photoFiles.get(key);return bytes?{arrayBuffer:async()=>bytes.buffer}:null},async delete(key){photoFiles.delete(key)}};let photoSchool=(await call('schools',{name:'Teste de foto autenticada',city:'Salvador'})).data;photoSchool=(await call('state',{school:photoSchool.id,type:'class',name:'A',students:1})).data;const image='data:image/jpeg;base64,'+readFileSync('public/bahia.jpg').toString('base64');assert(image.length>32768);photoSchool=(await call('state',{school:photoSchool.id,type:'candidate',classId:photoSchool.classes[0].id,name:'Teste',number:'01',category:0,photo:image})).data;const candidate=photoSchool.rounds[1].candidates[0];const photoUrl='candidate-photo?school='+photoSchool.id+'&candidateId='+candidate.id;await call(photoUrl,null,{cookie:'',status:401});const photoResponse=await handle(new Request(env.APP_URL+'/api/'+photoUrl,{headers:{Cookie:session}}),db,env);assert.equal(photoResponse.status,200);assert.equal(photoResponse.headers.get('Content-Type'),'image/jpeg');assert.deepEqual(new Uint8Array(await photoResponse.arrayBuffer()),new Uint8Array(readFileSync('public/bahia.jpg')));console.log('PASS autenticação de fotos: upload maior que 32 KB, armazenamento e acesso autenticado à imagem.');
