import {api} from './core.mjs';
const DOMAIN='enova.educacao.ba.gov.br',now=()=>Math.floor(Date.now()/1000),hex=b=>Array.from(new Uint8Array(b),v=>v.toString(16).padStart(2,'0')).join('');
export const randomToken=()=>hex(crypto.getRandomValues(new Uint8Array(32)));
export async function digest(value){return hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))}
export async function passwordHash(password,salt){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256));}
function eq(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let v=0;for(let i=0;i<a.length;i++)v|=a.charCodeAt(i)^b.charCodeAt(i);return v===0;}
const publicUser=u=>({id:u.id,email:u.email,name:u.name,verified:!!u.verified,testAccount:!!u.test_account,mustChange:!!u.must_change});
const json=(data,status=200,headers={})=>Response.json(data,{status,headers:{'Cache-Control':'no-store',...headers}});
function error(message,status=400){throw Object.assign(Error(message),{status})}
function validEmail(value){let email=String(value||'').trim().toLowerCase();if(email.length>254||!new RegExp('^[a-z0-9.!#$%&\x27*+/=?^_`{|}~-]+@'+DOMAIN.replaceAll('.','\\.')+'$').test(email))error('Use seu e-mail institucional @'+DOMAIN+'.');return email}
function validPassword(p){if(typeof p!=='string'||p.length<8||p.length>128)error('A nova senha deve ter entre 8 e 128 caracteres.');return p;}
const cookie=(request,value,ttl)=>`elege_session=${value}; HttpOnly; Path=/; SameSite=Strict; Max-Age=${ttl}${new URL(request.url).protocol==='https:'?'; Secure':''}`;
async function getSession(request,db){let raw=request.headers.get('Cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith('elege_session='))?.slice(14);if(!raw||!/^\w{64}$/.test(raw))return null;return db.prepare('SELECT users.*,sessions.hash AS session_hash FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.hash=? AND sessions.expires_at>? AND sessions.epoch=users.epoch').bind(await digest(raw),now()).first();}
async function rate(db,key,limit,period){let timestamp=now(),bucket=await digest(key+':'+Math.floor(timestamp/period));let row=await db.prepare('INSERT INTO rate_limits(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(bucket,timestamp+period).first();if(row.count>limit)error('Muitas tentativas. Aguarde alguns minutos e tente novamente.',429);}
export function mailProvider(env){if(env.EMAIL_PROVIDER)return env.EMAIL_PROVIDER;if(env.BREVO_API_KEY)return 'brevo';if(env.RESEND_API_KEY)return 'resend';if(env.EMAIL_WEBHOOK_URL)return 'webhook';return 'brevo';}
export function mailReady(env){if(env.MAILER)return true;switch(mailProvider(env)){case 'brevo':return !!(env.BREVO_API_KEY&&env.EMAIL_FROM);case 'resend':return !!(env.RESEND_API_KEY&&env.EMAIL_FROM);case 'webhook':return !!(env.EMAIL_WEBHOOK_URL?.startsWith('https://')&&env.EMAIL_WEBHOOK_TOKEN);default:return false;}}
export async function sendMail(env,to,kind,token){
 const origin=env.APP_URL;if(!origin)throw Error('APP_URL ausente');
 const link=origin+'/#'+(kind==='verify'?'verify':'reset')+'='+token;
 const message={to,subject:kind==='verify'?'Confirme seu e-mail — Eleições Escolares':'Redefina sua senha — Eleições Escolares',text:(kind==='verify'?'Confirme seu endereço institucional para acessar sua escola. O link expira em 24 horas.':'Você solicitou a recuperação de senha. O link expira em 30 minutos. Se não foi você, ignore este e-mail.')+'\n\n'+link};
 if(env.MAILER)return env.MAILER(message);
 if(!mailReady(env))throw Error('E-mail não configurado');
 let response;const provider=mailProvider(env);
 if(provider==='brevo')response=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{'api-key':env.BREVO_API_KEY,'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({sender:{email:env.EMAIL_FROM,name:env.EMAIL_FROM_NAME||'Eleições Escolares'},to:[{email:to,contactPixelTrackingConsent:false}],subject:message.subject,textContent:message.text}),signal:AbortSignal.timeout(15000)});
 else if(provider==='resend')response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+env.RESEND_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({from:env.EMAIL_FROM,to:[to],subject:message.subject,text:message.text}),signal:AbortSignal.timeout(15000)});
 else if(provider==='webhook')response=await fetch(env.EMAIL_WEBHOOK_URL,{method:'POST',headers:{Authorization:'Bearer '+env.EMAIL_WEBHOOK_TOKEN,'Content-Type':'application/json'},body:JSON.stringify(message),signal:AbortSignal.timeout(15000)});
 if(!response?.ok)throw Error('Falha do remetente '+(response?.status||'indisponível'));
}
async function deliver(env,to,kind,token,db){try{if(!mailReady(env))throw Error('E-mail não configurado');if(!env.MAILER&&mailProvider(env)==='brevo'){// Cap application send attempts to the free plan allowance, across all callers.
const day=Math.floor(now()/86400),key='email-brevo:'+day;const quota=await db.prepare('INSERT INTO rate_limits(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,(day+1)*86400).first();if(quota.count>300)throw Error('Limite gratuito diário atingido');}await sendMail(env,to,kind,token);return true}catch{console.error('Não foi possível enviar o e-mail de autenticação.');return false}}
export async function handle(request,db,env={}){const url=new URL(request.url);if(!url.pathname.startsWith('/api/'))return null;try{const isPost=request.method==='POST';if(!['GET','POST'].includes(request.method))error('Método não permitido.',405);if(isPost){const origin=request.headers.get('Origin');if(origin!==(env.APP_URL||url.origin))error('Origem não autorizada.',403);if(!request.headers.get('Content-Type')?.startsWith('application/json'))error('Envie dados JSON.',415);}let text=isPost?await request.clone().text():'';if(text.length>32768)error('Requisição muito grande.',413);let b=text?JSON.parse(text):{};let path=url.pathname;const ip=request.headers.get('CF-Connecting-IP')||'local';if(path.startsWith('/api/auth/')&&isPost)await rate(db,'auth-ip:'+ip,100,3600);
if(path==='/api/auth/me'){if(isPost)error('Método não permitido.',405);let u=await getSession(request,db);return json({user:u?publicUser(u):null,emailConfigured:mailReady(env),emailProvider:mailProvider(env)});}
if(path==='/api/auth/register'&&isPost){const email=validEmail(b.email),password=validPassword(b.password);if(!b.name?.trim()||!b.schoolName?.trim()||!b.city?.trim())error('Informe seu nome, escola e município.');if(env.REGISTRATION_OPEN==='false')error('O cadastro de gestores está temporariamente fechado.',403);await rate(db,'register:'+email,3,3600);if(await db.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({message:'Se você já possui uma conta, entre ou solicite a recuperação de senha.',emailConfigured:mailReady(env),emailProvider:mailProvider(env)});let id=crypto.randomUUID(),salt=randomToken(),token=randomToken(),hash=await passwordHash(password,salt);const {fresh}=await import('./core.mjs');let schoolId=crypto.randomUUID(),s=fresh(b.schoolName.trim().slice(0,120),b.city.trim().slice(0,80),(b.inep||'').slice(0,20));await db.batch([db.prepare('INSERT INTO users(id,email,name,password_hash,salt,verify_hash,verify_expires,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(id,email,b.name.trim().slice(0,100),hash,salt,await digest(token),now()+86400,now()),db.prepare('INSERT INTO schools(id,owner,payload) VALUES(?,?,?)').bind(schoolId,id,JSON.stringify(s))]);let sent=await deliver(env,email,'verify',token,db);return json({message:sent?'Cadastro recebido. Confirme seu e-mail para entrar.':'Cadastro salvo. O envio de confirmação está temporariamente indisponível; use Reenviar confirmação quando o remetente estiver configurado.',emailSent:sent,emailConfigured:mailReady(env),emailProvider:mailProvider(env)},201);}
if(path==='/api/auth/login'&&isPost){const email=validEmail(b.email);await rate(db,'login:'+email,10,900);let u=await db.prepare('SELECT * FROM users WHERE email=?').bind(email).first();let hash=await passwordHash(typeof b.password==='string'?b.password.slice(0,128):'',u?.salt||'unknown-user');if(!u||!eq(hash,u.password_hash))error('E-mail ou senha incorretos.',401);if(!u.verified)error('Confirme seu e-mail antes de entrar. Use Reenviar confirmação se necessário.',403);let token=randomToken();await db.prepare('INSERT INTO sessions(hash,user_id,epoch,expires_at) VALUES(?,?,?,?)').bind(await digest(token),u.id,u.epoch,now()+43200).run();return json({user:publicUser(u)},200,{'Set-Cookie':cookie(request,token,43200)});}
if(path==='/api/auth/resend'&&isPost){const email=validEmail(b.email);await rate(db,'resend:'+email,3,3600);if(!mailReady(env))error('O remetente de e-mails ainda não foi configurado.',503);let u=await db.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(u&&!u.verified){let token=randomToken();await db.prepare('UPDATE users SET verify_hash=?,verify_expires=? WHERE id=? AND verified=0').bind(await digest(token),now()+86400,u.id).run();if(!await deliver(env,email,'verify',token,db))error('O serviço de e-mail não respondeu. Tente novamente depois.',503);}return json({message:'Se houver uma conta aguardando confirmação, enviaremos um novo link.'});}
if(path==='/api/auth/verify'&&isPost){if(!/^[a-f0-9]{64}$/.test(b.token||''))error('Link de confirmação inválido.');let hash=await digest(b.token);let result=await db.prepare('UPDATE users SET verified=1,verify_hash=NULL,verify_expires=NULL WHERE verify_hash=? AND verify_expires>? AND verified=0').bind(hash,now()).run();if(result.meta.changes!==1)error('Link inválido, expirado ou já utilizado. Solicite nova confirmação.');return json({message:'E-mail confirmado. Você já pode entrar.'});}
if(path==='/api/auth/forgot'&&isPost){const email=validEmail(b.email);await rate(db,'forgot:'+email,3,3600);if(!mailReady(env))error('O remetente de e-mails ainda não foi configurado.',503);let u=await db.prepare('SELECT * FROM users WHERE email=? AND verified=1').bind(email).first();if(u){let token=randomToken();await db.prepare('UPDATE users SET reset_hash=?,reset_expires=? WHERE id=?').bind(await digest(token),now()+1800,u.id).run();if(!await deliver(env,email,'reset',token,db))error('O serviço de e-mail não respondeu. Tente novamente depois.',503);}return json({message:'Se existir uma conta confirmada, enviaremos as instruções de recuperação.'});}
if(path==='/api/auth/reset'&&isPost){validPassword(b.password);if(!/^[a-f0-9]{64}$/.test(b.token||''))error('Link de recuperação inválido.');let hash=await digest(b.token),u=await db.prepare('SELECT id FROM users WHERE reset_hash=? AND reset_expires>?').bind(hash,now()).first();if(!u)error('Link inválido, expirado ou já utilizado.');let salt=randomToken(),pw=await passwordHash(b.password,salt);let result=await db.prepare('UPDATE users SET password_hash=?,salt=?,epoch=epoch+1,must_change=0,reset_hash=NULL,reset_expires=NULL WHERE id=? AND reset_hash=? AND reset_expires>?').bind(pw,salt,u.id,hash,now()).run();if(result.meta.changes!==1)error('Link já utilizado.');return json({message:'Senha redefinida. Entre com a nova senha.'},200,{'Set-Cookie':cookie(request,'',0)});}
const user=await getSession(request,db);
if(path==='/api/auth/logout'&&isPost){if(user)await db.prepare('DELETE FROM sessions WHERE hash=?').bind(user.session_hash).run();return json({ok:true},200,{'Set-Cookie':cookie(request,'',0)});}
if(path==='/api/auth/change-password'&&isPost){if(!user)error('Entre para alterar sua senha.',401);validPassword(b.password);if(!eq(await passwordHash(String(b.currentPassword||'').slice(0,128),user.salt),user.password_hash))error('Senha atual incorreta.');if(eq(await passwordHash(b.password,user.salt),user.password_hash))error('Escolha uma senha diferente da atual.');let salt=randomToken(),pw=await passwordHash(b.password,salt);let result=await db.prepare('UPDATE users SET password_hash=?,salt=?,epoch=epoch+1,must_change=0,reset_hash=NULL,reset_expires=NULL WHERE id=? AND epoch=? AND password_hash=?').bind(pw,salt,user.id,user.epoch,user.password_hash).run();if(result.meta.changes!==1)error('Sua conta foi atualizada. Entre novamente.',409);return json({message:'Senha alterada. Entre novamente; as sessões anteriores foram encerradas.'},200,{'Set-Cookie':cookie(request,'',0)});}
if(path.startsWith('/api/auth/'))error('Caminho não encontrado.',404);
if(!['/api/ballot','/api/vote'].includes(path)){if(!user)error('Entre para acessar sua escola.',401);if(user.must_change)error('Altere a senha inicial antes de acessar a gestão.',403);if(!user.verified)error('Confirme seu e-mail.',403);}return api(request,db,user?.id||null);
}catch(e){if(!e.status){console.error('Falha na autenticação:',e.name);return json({error:'Não foi possível concluir a operação. Tente novamente.'},500)}return json({error:e.message},e.status)}}
