export const categories=['Geral','Quilombola','LGBTQIAPN+','Do Campo','PCD'];
const fail=m=>{throw Error(m)},required=(x,m)=>{if(!x)fail(m)};
export function ranking(s,round=s.round){let r=s.rounds[round];let groups={};for(let c of r.candidates){let k=(round===1?c.classId:'escola')+'|'+c.category;(groups[k]??=[]).push({...c,votes:r.tally[c.id]||0})}return Object.entries(groups).map(([key,list])=>{list.sort((a,b)=>b.votes-a.votes||a.name.localeCompare(b.name));const valid=list.reduce((a,c)=>a+c.votes,0),tie=valid===0||list.length>1&&list[0].votes===list[1].votes;const viceTie=round===1&&list[0].category===0&&list.length>2&&list[1].votes===list[2].votes;return {key,list,valid,tie,viceTie,winner:tie?null:list[0],vice:round===1&&list[0].category===0&&!tie&&!viceTie?list[1]||null:null}})}
// Numeric codes are unique within the school, including previous rounds.
export function shortCodes(s,tokens){const reserved=new Set(Object.values(s.rounds).flatMap(r=>r.tokens.flatMap(t=>[t.code,t.legacyCode].filter(Boolean))));required(tokens.length<=100000,'O limite por turno é de 100 mil eleitores.');const random=new Uint32Array(1);for(const t of tokens){let code;do{do{crypto.getRandomValues(random)}while(random[0]>=4294000000);code=String(random[0]%1000000).padStart(6,'0')}while(reserved.has(code));reserved.add(code);if(t.code)t.legacyCode=t.code;t.code=code;}}
const matchesCode=(t,code)=>t.code===code||!!t.legacyCode&&t.legacyCode===code;
export function action(s,a){const r=s.rounds[s.round];required(!s.finished,'Processo encerrado.');switch(a.type){case 'class':required(s.round===1&&r.phase==='registration','Cadastro de turmas encerrado.');required(a.name?.trim()&&Number.isInteger(+a.students)&&+a.students>0&&+a.students<=1000,'Informe turma e quantidade de estudantes (1 a 1000).');required(!s.classes.some(c=>c.name.toLowerCase()===a.name.trim().toLowerCase()),'Turma já cadastrada.');s.classes.push({id:crypto.randomUUID(),name:a.name.trim().slice(0,80),students:+a.students,concluding:!!a.concluding});break;
case 'candidate':required(r.phase==='registration'&&s.round!==2,'Inscrições encerradas.');required(a.name?.trim()&&Number.isInteger(+a.category)&&categories[+a.category],'Informe nome e categoria.');required(s.classes.some(c=>c.id===a.classId)||s.round===3,'Escolha uma turma.');required(!r.candidates.some(c=>c.number===a.number),'Número já utilizado neste turno.');required(/^\d{2}$/.test(a.number),'Use um número com dois dígitos.');r.candidates.push({id:crypto.randomUUID(),name:a.name.trim().slice(0,100),category:+a.category,classId:s.round===1?a.classId:null,number:a.number});break;
case 'skip':required(s.round===2&&r.phase==='registration'&&!r.candidates.length,'Só é possível dispensar o segundo turno quando não houver líderes elegíveis.');r.phase='closed';r.opened=r.closed=new Date().toISOString();r.results=[];r.skipped=true;break;
case 'open':required(r.phase==='registration','Votação já aberta.');required(s.classes.length,'Cadastre as turmas.');if(s.round===1)required(s.classes.every(c=>r.candidates.some(p=>p.classId===c.id&&p.category===0)),'Cada turma precisa de pelo menos um candidato a Líder da Turma.');required(r.candidates.length,'Não há candidatos elegíveis neste turno.');r.phase='voting';r.opened=new Date().toISOString();r.tokens=[];for(let c of s.classes)for(let i=0;i<c.students;i++)r.tokens.push({classId:c.id,used:false});shortCodes(s,r.tokens);break;
case 'shorten-codes':required(r.phase==='voting','Abra a votação primeiro.');shortCodes(s,r.tokens.filter(t=>!t.used&&!/^\d{6}$/.test(t.code)));break;
case 'close':required(r.phase==='voting','Votação não está aberta.');r.phase='closed';r.closed=new Date().toISOString();r.results=ranking(s);break;
case 'next':required(r.phase==='closed','Encerre a votação antes de avançar.');required(!r.results.some(g=>g.tie||g.viceTie),'Resolva os empates antes de avançar.');if(s.round===3){s.finished=true;break;}s.round++;if(s.round===2){s.rounds[2].candidates=r.results.filter(g=>g.winner&&!s.classes.find(c=>c.id===g.winner.classId)?.concluding).map(g=>({...g.winner,id:crypto.randomUUID(),votes:undefined}));}break;
case 'resolve':required(r.phase==='closed','Encerre a votação.');required(a.reason?.trim(),'Registre a justificativa da comissão.');let g=r.results.find(g=>g.key===a.key);required(g,'Resultado não encontrado.');let max=g.list[0].votes;required(g.list.some(c=>c.id===a.winner&&c.votes===max),'Selecione um candidato empatado na primeira posição.');g.winner=g.list.find(c=>c.id===a.winner);g.tie=false;if(s.round===1&&g.list[0].category===0&&g.list.length>1){const remaining=g.list.filter(c=>c.id!==a.winner),vmax=Math.max(...remaining.map(c=>c.votes));required(remaining.some(c=>c.id===a.vice&&c.votes===vmax),'Selecione o vice entre os empatados na segunda posição.');g.vice=remaining.find(c=>c.id===a.vice);g.viceTie=false;}g.resolution=a.reason.trim().slice(0,1000);break;
default:fail('Ação inválida.')}return s;}
export function cast(s,code,choices){const r=s.rounds[s.round];required(r.phase==='voting','Votação indisponível.');let t=r.tokens.find(t=>matchesCode(t,code));required(t&&!t.used,'Código inválido ou já utilizado.');const cs=r.candidates.filter(c=>s.round!==1||c.classId===t.classId),cats=[...new Set(cs.map(c=>c.category))];required(choices&&Object.keys(choices).length===cats.length,'Vote em todos os cargos disponíveis.');for(let cat of cats){let id=choices[cat];required(id==='blank'||id==='null'||cs.some(c=>c.id===id&&c.category===cat),'Candidato inválido.');const key=(s.round===1?t.classId:'escola')+'|'+cat;if(id==='blank'||id==='null'){let k=key+'|'+id;r.tally[k]=(r.tally[k]||0)+1;}else r.tally[id]=(r.tally[id]||0)+1;}t.used=true;r.turnout++;return s;}
export const fresh=(name,city,inep)=>({name,city,inep,classes:[],round:1,finished:false,created:new Date().toISOString(),rounds:Object.fromEntries([1,2,3].map(i=>[i,{phase:'registration',candidates:[],tally:{},tokens:[],turnout:0}]))});
export async function api(request,db,owner){const url=new URL(request.url),body=request.method==='POST'?await request.json():{},id=body.school||url.searchParams.get('school');const response=(x,status=200)=>Response.json(x,{status,headers:{'Cache-Control':'no-store'}});try{if(url.pathname==='/api/schools'){required(owner,'Entre para acessar a gestão.');if(request.method==='POST'){required(body.name?.trim()&&body.city?.trim(),'Informe escola e município.');let id=crypto.randomUUID();let s=fresh(body.name.trim().slice(0,120),body.city.trim().slice(0,80),(body.inep||'').slice(0,20));await db.prepare('INSERT INTO schools(id,owner,payload) VALUES(?,?,?)').bind(id,owner,JSON.stringify(s)).run();return response({id,...s});}return response((await db.prepare('SELECT id,payload FROM schools WHERE owner=?').bind(owner).all()).results.map(x=>({id:x.id,name:JSON.parse(x.payload).name})));}
let row=await db.prepare('SELECT * FROM schools WHERE id=?').bind(id).first();required(row,'Escola não encontrada.');let s=JSON.parse(row.payload);if(url.pathname==='/api/ballot'){let t=s.rounds[s.round].tokens.find(t=>matchesCode(t,body.code||url.searchParams.get('code')));required(s.rounds[s.round].phase==='voting'&&t&&!t.used,'Código inválido, já utilizado ou votação encerrada.');return response({name:s.name,round:s.round,className:s.classes.find(c=>c.id===t.classId)?.name,candidates:s.rounds[s.round].candidates.filter(c=>s.round!==1||c.classId===t.classId)});}
if(url.pathname==='/api/vote')cast(s,body.code,body.choices);else{required(owner&&row.owner===owner,'Acesso restrito à coordenação da escola.');if(request.method==='GET')return response({id,...s});action(s,body);}if(request.method==='POST'){const res=await db.prepare('UPDATE schools SET payload=?,version=version+1 WHERE id=? AND version=?').bind(JSON.stringify(s),id,row.version).run();required(res.meta.changes===1,'Outra operação ocorreu. Atualize e tente novamente.');}return response(url.pathname==='/api/vote'?{ok:true}:{id,...s});}catch(e){return response({error:e.message},400)}}
